/* Generated by Yosys 0.45 (git sha1 9ed031ddd, g++ 11.2.0 -fPIC -O3) */

(* top =  1  *)
(* src = "src/fsm.sv:1.1-50.10" *)
module fsm(CLK, nRST, data, accept);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "src/fsm.sv:2.11-2.14" *)
  input CLK;
  wire CLK;
  (* src = "src/fsm.sv:4.12-4.18" *)
  output accept;
  wire accept;
  (* src = "src/fsm.sv:3.11-3.15" *)
  input data;
  wire data;
  (* src = "src/fsm.sv:2.16-2.20" *)
  input nRST;
  wire nRST;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\S0" *)
  (* enum_value_001 = "\\S1" *)
  (* enum_value_010 = "\\S2" *)
  (* enum_value_011 = "\\S3" *)
  (* enum_value_100 = "\\S4" *)
  (* src = "src/fsm.sv:20.20-20.24" *)
  (* wiretype = "\\state_t" *)
  wire [2:0] next;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\S0" *)
  (* enum_value_001 = "\\S1" *)
  (* enum_value_010 = "\\S2" *)
  (* enum_value_011 = "\\S3" *)
  (* enum_value_100 = "\\S4" *)
  (* src = "src/fsm.sv:20.13-20.18" *)
  (* wiretype = "\\state_t" *)
  wire [2:0] state;
  INV_X1 _20_ (
    .A(data),
    .ZN(_01_)
  );
  INV_X1 _21_ (
    .A(state[0]),
    .ZN(_02_)
  );
  NOR3_X1 _22_ (
    .A1(state[2]),
    .A2(_02_),
    .A3(state[1]),
    .ZN(_03_)
  );
  OR3_X1 _23_ (
    .A1(state[2]),
    .A2(_02_),
    .A3(state[1]),
    .ZN(_04_)
  );
  NOR2_X1 _24_ (
    .A1(state[0]),
    .A2(state[1]),
    .ZN(_05_)
  );
  NAND2_X1 _25_ (
    .A1(_00_),
    .A2(_05_),
    .ZN(_06_)
  );
  INV_X1 _26_ (
    .A(_06_),
    .ZN(accept)
  );
  AND3_X1 _27_ (
    .A1(state[0]),
    .A2(state[1]),
    .A3(_00_),
    .ZN(_07_)
  );
  NOR2_X1 _28_ (
    .A1(state[2]),
    .A2(state[0]),
    .ZN(_08_)
  );
  NAND2_X1 _29_ (
    .A1(state[2]),
    .A2(_05_),
    .ZN(_09_)
  );
  AOI21_X1 _30_ (
    .A(_07_),
    .B1(_08_),
    .B2(state[1]),
    .ZN(_10_)
  );
  AND4_X1 _31_ (
    .A1(_04_),
    .A2(_06_),
    .A3(_09_),
    .A4(_10_),
    .ZN(_11_)
  );
  NOR3_X1 _32_ (
    .A1(state[0]),
    .A2(state[1]),
    .A3(_00_),
    .ZN(_12_)
  );
  NOR2_X1 _33_ (
    .A1(_01_),
    .A2(_12_),
    .ZN(_13_)
  );
  AOI21_X1 _34_ (
    .A(data),
    .B1(state[1]),
    .B2(_08_),
    .ZN(_14_)
  );
  NOR3_X1 _35_ (
    .A1(_11_),
    .A2(_13_),
    .A3(_14_),
    .ZN(next[2])
  );
  NAND2_X1 _36_ (
    .A1(data),
    .A2(_07_),
    .ZN(_15_)
  );
  OAI211_X1 _37_ (
    .A(_04_),
    .B(_15_),
    .C1(_09_),
    .C2(data),
    .ZN(next[1])
  );
  OAI21_X1 _38_ (
    .A(_01_),
    .B1(_07_),
    .B2(_12_),
    .ZN(_16_)
  );
  OAI21_X1 _39_ (
    .A(data),
    .B1(_03_),
    .B2(accept),
    .ZN(_17_)
  );
  AOI21_X1 _40_ (
    .A(_11_),
    .B1(_16_),
    .B2(_17_),
    .ZN(next[0])
  );
  (* src = "src/fsm.sv:23.5-29.8" *)
  DFFR_X1 _41_ (
    .CK(CLK),
    .D(next[0]),
    .Q(state[0]),
    .QN(_18_),
    .RN(nRST)
  );
  (* src = "src/fsm.sv:23.5-29.8" *)
  DFFR_X1 _42_ (
    .CK(CLK),
    .D(next[1]),
    .Q(state[1]),
    .QN(_19_),
    .RN(nRST)
  );
  (* src = "src/fsm.sv:23.5-29.8" *)
  DFFR_X1 _43_ (
    .CK(CLK),
    .D(next[2]),
    .Q(state[2]),
    .QN(_00_),
    .RN(nRST)
  );
endmodule
